# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [38]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import json

# Import API key
from config import google_key
gmaps.configure(api_key=google_key)

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [13]:
# creating the file path and loading the CSV file into a DataFrame
path = "C:\\Users\\Derek\\Desktop\\"
file = os.path.join(path, "python-api-challenge", "cities.csv")
city_df = pd.read_csv(file)
city_df.head()

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,Taoudenni,22.6783,-3.9836,87.53,13,30,7.83,ML,1651620261
1,Lata,40.1629,-8.3327,58.08,74,20,4.50,PT,1651620261
2,Haukipudas,65.1765,25.3523,30.25,77,33,4.36,FI,1651620262
3,Rikitea,-23.1203,-134.9692,77.31,79,68,17.34,PF,1651620262
4,Vestmannaeyjar,63.4427,-20.2734,41.63,83,79,26.13,IS,1651620263

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [14]:
# creating variable to hold only the latitude and longitude as well as converting the humidity column to a float
location = city_df[["Lat", "Lng"]]
humidity = city_df["Humidity"].astype(float)

In [19]:
# creating the heatmap
figure = gmaps.figure()
humidity_layer = gmaps.heatmap_layer(location, weights=humidity, dissipating=False, max_intensity=humidity.max(),
                                 point_radius=2)
figure.add_layer(humidity_layer)
figure

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [53]:
# narrowing down the city list based on vacation requirements
reduced_temp = city_df.loc[(city_df["Max Temp"] > 60) & (city_df["Max Temp"] < 65)]
reduced = reduced_temp.loc[reduced_temp["Humidity"] <= 45]
hotel_df = reduced.loc[reduced["Cloudiness"] < 30]
hotel_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
82,Edson,53.5835,-116.4356,62.74,31,0,3.44,CA,1651620093
211,San Juan,-31.5375,-68.5364,64.72,26,0,5.23,AR,1651620326
227,Tottori-shi,35.5000,134.2333,64.47,39,0,10.36,JP,1651620346
231,Yulara,-25.2406,130.9889,64.24,45,0,13.80,AU,1651620347
426,Nokaneng,-19.6667,22.2667,60.55,43,3,6.42,BW,1651620424
498,Yumen,40.2833,97.2000,61.39,12,3,6.69,CN,1651620317

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [54]:
# creating the parameters
params = {"radius": 5000, 
          "keyword": "hotel",
          "key": google_key}

# creating the for loop to run through the API to pull the hotel information
for index, row in hotel_df.iterrows():
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    hotel_info = requests.get(base_url, params=params)
    hotel_info = hotel_info.json()
    #print(json.dumps(hotel_info, indent=4, sort_keys=True))
    
    try:
        hotel_df.loc[index, "Hotel Name"] = hotel_info["results"][0]["name"]
    except:
        print("Missing result/skipping")

C:\Users\Derek\anaconda3\lib\site-packages\pandas\core\indexing.py:1684: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = infer_fill_value(value)
C:\Users\Derek\anaconda3\lib\site-packages\pandas\core\indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

Missing result/skipping
Missing result/skipping

In [55]:
hotel_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
82,Edson,53.5835,-116.4356,62.74,31,0,3.44,CA,1651620093,"Holiday Inn Express & Suites Edson, an IHG Hotel"
211,San Juan,-31.5375,-68.5364,64.72,26,0,5.23,AR,1651620326,Del Bono Park Hotel Spa & Casino
227,Tottori-shi,35.5000,134.2333,64.47,39,0,10.36,JP,1651620346,Hotel New Otani Tottori
231,Yulara,-25.2406,130.9889,64.24,45,0,13.80,AU,1651620347,Desert Gardens Hotel - Ayers Rock Resort
426,Nokaneng,-19.6667,22.2667,60.55,43,3,6.42,BW,1651620424,NaN
498,Yumen,40.2833,97.2000,61.39,12,3,6.69,CN,1651620317,NaN

In [56]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [59]:
# Add marker layer ontop of heat map
figure2 = gmaps.figure()

markers = gmaps.marker_layer(locations, info_box_content=hotel_info)
humidity_layer = gmaps.heatmap_layer(location, weights=humidity, dissipating=False, max_intensity=humidity.max(),
                                 point_radius=2)
figure2.add_layer(humidity_layer)
figure2.add_layer(markers)

# Display figure
figure2

Figure(layout=FigureLayout(height='420px'))